# Generated by Django 3.2.4 on 2021-07-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('respond', models.CharField(max_length=300)),
                ('pub_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('pub_data',),
            },
        ),
    ]
