# Generated by Django 3.2.4 on 2021-08-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('pub_date',)},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
